---
abstract: 'DBIx Class Result ColumnData'
author:
  - 'Nicolas Oudard'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Result-ColumnData
provides:
  DBIx::Class::Result::ColumnData:
    file: lib/DBIx/Class/Result/ColumnData.pm
    version: 0.07
requires:
  DBIx::Class: 0.08127
  DateTime: 0.65
  DateTime::Format::SQLite: 0.11
  SQL::Translator: 0.11007
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
