--- #YAML:1.0
name:               DBIx-Class-Result-ColumnData
version:            0.05
abstract:           ~
author:
    - Nicolas Oudard <nicolas@oudard.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:             0.65
    DateTime::Format::SQLite:  0.11
    DBIx::Class:          0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
